### ISSUE TITLE
Require documentation on gaeUpdate task

### ISSUE THREAD

**Issue by bond-** [bmuschko/gradle-gae-plugin#55]
gaeUpdate task is failing on my machine, I believe there is some configuration that I'm missing.

Please update plugin readme/wiki with more documentation.

Gradle logs:

```
The TaskContainer.add() method has been deprecated and is scheduled to be removed in Gradle 2.0. Please use the create() method instead.
The ConfigurationContainer.add() method has been deprecated and is scheduled to be removed in Gradle 2.0. Please use the create() method instead.
The SourceSetContainer.add() method has been deprecated and is scheduled to be removed in Gradle 2.0. Please use the create() method instead.
The groovy configuration has been deprecated and is scheduled to be removed in Gradle 2.0. Typically, usages of 'groovy' can simply be replaced with 'compile'. In some cases, it may be necessary to additionally configure the 'groovyClasspath' property of GroovyCompile and Groovydoc tasks.
:gaeDownloadSdk
:compileJava UP-TO-DATE
:compileGroovy UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:gaelykPrecompileGroovlet
:gaelykPrecompileTemplate
:fatJarPrepareFiles
:fatJar
:slimWar
:gaeExplodeWar
:gaeUpdateAug 09, 2013 10:14:18 PM com.google.appengine.tools.info.RemoteVersionFactory getVersion
INFO: Unable to access https://data-converter.appspot.com/api/updatecheck?runtime=java&release=1.8.3&timestamp=1375298383&api_versions=[]
java.io.IOException: Server returned HTTP response code: 500 for URL: https://data-converter.appspot.com/api/updatecheck/?runtime=java&release=1.8.3&timestamp=1375298383&api_versions=%5B%5D
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1625)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
    at java.net.URL.openStream(URL.java:1037)
    at com.google.appengine.tools.info.RemoteVersionFactory.getVersion(RemoteVersionFactory.java:76)
    at com.google.appengine.tools.info.UpdateCheck.getApplicationVersionInfo(UpdateCheck.java:151)
    at com.google.appengine.tools.info.UpdateCheck.maybePrintNagScreen(UpdateCheck.java:361)
    at com.google.appengine.tools.admin.AppCfg.<init>(AppCfg.java:182)
    at com.google.appengine.tools.admin.AppCfg.<init>(AppCfg.java:121)
    at com.google.appengine.tools.admin.AppCfg.main(AppCfg.java:117)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
    at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.invoke(StaticMetaMethodSite.java:43)
    at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:88)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
    at org.gradle.api.plugins.gae.task.appcfg.GaeAppConfigTaskTemplate.runAppConfig(GaeAppConfigTaskTemplate.groovy:66)
    at org.gradle.api.plugins.gae.task.appcfg.GaeAppConfigTaskTemplate$runAppConfig.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
    at org.gradle.api.plugins.gae.task.appcfg.GaeAppConfigTaskTemplate$AppConfigRunnable.run(GaeAppConfigTaskTemplate.groovy:125)
    at java.lang.Thread.run(Thread.java:724)


Reading application configuration data...
Aug 09, 2013 10:14:18 PM com.google.apphosting.utils.config.AppEngineWebXmlReader readAppEngineWebXml
INFO: Successfully processed /home/<user>/projects/data-conv/build/exploded-war/WEB-INF/appengine-web.xml
Aug 09, 2013 10:14:18 PM com.google.apphosting.utils.config.AbstractConfigXmlReader readConfigXml
INFO: Successfully processed /home/<user>/projects/data-conv/build/exploded-war/WEB-INF/web.xml


Beginning interaction for module default...

com.google.appengine.tools.admin.HttpIoException: Error posting to URL: https://data-converter.appspot.com/api/appversion/getresourcelimits?app_id=data-converter&version=1&
302 Found

Unable to update app: Error posting to URL: https://data-converter.appspot.com/api/appversion/getresourcelimits?app_id=data-converter&version=1&
302 Found

Please see the logs [/tmp/appcfg7183167981363025449.log] for further information.

Process finished with exit code 1
```

**Comment by bond-** [comment]
I checked the gaelogs and this /api/\* routes seems to caught by the application. BTW I'm just using the gaelyk template project.

**Comment by bond-** [comment]
I finally understood what mistake I did.

Do not override the server property

```
gae {
    ...
    appcfg {
        ...
        // do not do this
        server = '<my-app.appspot.com>'
        ...
    }
    ...
}
```
