### ISSUE TITLE
Upload task should enable JAR splitting by default

### ISSUE THREAD

**Issue by bmuschko** [bmuschko/gradle-gae-plugin#8]
For uploading the WAR file to GAE you might run into a [size constraint](http://code.google.com/p/googleappengine/issues/detail?id=5805) if your artifact is really big. This is a known issue. Google recommends setting the option `--enable_jar_splitting` to improve this.

For more information see this posting on the [Gaelyk Google Groups](http://groups.google.com/group/gaelyk/browse_thread/thread/35cd16e57a734aba).

**Comment by drindt** [comment]
The changelog says its enabled by default, but i got this message during the deploy:

```
com.google.appengine.tools.admin.LocalIOException: Jar /tmp/appcfg3942121943129002742.tmp/WEB-INF/lib/gwt-user-2.7.0.jar is too large. Consider using --enable_jar_splitting.
Unable to update app: Jar /tmp/appcfg3942121943129002742.tmp/WEB-INF/lib/gwt-user-2.7.0.jar is too large. Consider using --enable_jar_splitting.
Please see the logs [/tmp/appcfg6370452515418377347.log] for further information.
```

the log contains:

```
Unable to update:
com.google.appengine.tools.admin.LocalIOException: Jar /tmp/appcfg2427251093703000787.tmp/WEB-INF/lib/gwt-user-2.7.0.jar is too large. Consider using --enable_jar_splitting.
    at com.google.appengine.tools.admin.AppVersionUpload.scanFiles(AppVersionUpload.java:249)
    at com.google.appengine.tools.admin.AppVersionUpload.uploadFilesTransaction(AppVersionUpload.java:175)
    at com.google.appengine.tools.admin.AppVersionUpload.doUpload(AppVersionUpload.java:153)
    at com.google.appengine.tools.admin.AppAdminImpl.doUpdate(AppAdminImpl.java:474)
    at com.google.appengine.tools.admin.AppAdminImpl.update(AppAdminImpl.java:55)
    at com.google.appengine.tools.admin.AppCfg$UpdateAction.execute(AppCfg.java:1361)
    at com.google.appengine.tools.admin.AppCfg.executeAction(AppCfg.java:332)
    at com.google.appengine.tools.admin.AppCfg.<init>(AppCfg.java:213)
    at com.google.appengine.tools.admin.AppCfg.<init>(AppCfg.java:124)
    at com.google.appengine.tools.admin.AppCfg.main(AppCfg.java:120)
com.google.appengine.tools.admin.AdminException: Unable to update app: Jar /tmp/appcfg2427251093703000787.tmp/WEB-INF/lib/gwt-user-2.7.0.jar is too large. Consider using --enable_jar_splitting.
    at com.google.appengine.tools.admin.AppAdminImpl.doUpdate(AppAdminImpl.java:480)
    at com.google.appengine.tools.admin.AppAdminImpl.update(AppAdminImpl.java:55)
    at com.google.appengine.tools.admin.AppCfg$UpdateAction.execute(AppCfg.java:1361)
    at com.google.appengine.tools.admin.AppCfg.executeAction(AppCfg.java:332)
    at com.google.appengine.tools.admin.AppCfg.<init>(AppCfg.java:213)
    at com.google.appengine.tools.admin.AppCfg.<init>(AppCfg.java:124)
    at com.google.appengine.tools.admin.AppCfg.main(AppCfg.java:120)
Caused by: com.google.appengine.tools.admin.LocalIOException: Jar /tmp/appcfg2427251093703000787.tmp/WEB-INF/lib/gwt-user-2.7.0.jar is too large. Consider using --enable_jar_splitting.
    at com.google.appengine.tools.admin.AppVersionUpload.scanFiles(AppVersionUpload.java:249)
    at com.google.appengine.tools.admin.AppVersionUpload.uploadFilesTransaction(AppVersionUpload.java:175)
    at com.google.appengine.tools.admin.AppVersionUpload.doUpload(AppVersionUpload.java:153)
    at com.google.appengine.tools.admin.AppAdminImpl.doUpdate(AppAdminImpl.java:474)
    ... 6 more
```

The file "gwt-user-2.7.0.jar" is around 31M.
I am unable to deploy at the moment. It would be great to get a hint how to solve this. Thank you very much.

**Comment by bmuschko** [comment]
This repository is not maintained anymore. Please address the issue in the [new repository](https://github.com/GoogleCloudPlatform/gradle-appengine-plugin) of the plugin.

**Comment by varunvajpayee** [comment]
you should not upload this jar. This is only be supposed to be used in development of the app (only at compile time). This will be provided by app engine at run time. Try using "provided" as scope in maven for this jar.
